In [1]:
import leafmap
import geopandas as gpd
from geospatial_tools import DATA_DIR
from geospatial_tools.planetary_computer.sentinel_2 import BestProductsForFeatures, download_and_process_sentinel2_asset
from geospatial_tools.raster import clip_raster_with_polygon
from geospatial_tools.stac import Asset
from geospatial_tools.utils import get_yaml_config, download_url, unzip_file
from geospatial_tools.vector import create_vector_grid_parallel, to_geopackage, select_polygons_by_location

## Base data

The USA polygon is base off 2018's `cb_2018_us_nation_20m` shapefile, taken from here: 
https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html

It was then processed using QGIS to keep only the contiguous states, without any islands.

The Sentinel 2 grid was taken from the kml file found here: 
https://sentiwiki.copernicus.eu/web/s2-products

Below is some code to help with the download part.

### Downloading data
Let's download our source data

In [2]:
file_configs = get_yaml_config("data_file_links")
raw_usa_polygon_path = file_configs["united_states_polygon"]["url"]
raw_s2_tiling_grid_path = file_configs["sentinel_2_tiling_grid"]["url"]
download_list = {"raw_usa_polygon": raw_usa_polygon_path, "raw_s2_tiling_grid": raw_s2_tiling_grid_path}
file_list = [download_url(url=url, filename=f"{DATA_DIR}/{key}.zip") for key, url in download_list.items()]

file_list

[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Yaml config file [/home/dev/projects/geospatial-tools/configs/data_file_links.yaml] found.
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Loading YAML config file [/home/dev/projects/geospatial-tools/configs/data_file_links.yaml].
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] File [/home/dev/projects/geospatial-tools/data/raw_usa_polygon.zip] already exists. Skipping download.
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] File [/home/dev/projects/geospatial-tools/data/raw_s2_tiling_grid.zip] already exists. Skipping download.

[PosixPath('/home/dev/projects/geospatial-tools/data/raw_usa_polygon.zip'),
 PosixPath('/home/dev/projects/geospatial-tools/data/raw_s2_tiling_grid.zip')]

In [3]:
[unzip_file(zip_path=f, extract_to=DATA_DIR) for f in file_list]

[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.shp.ea.iso.xml]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.shp.iso.xml]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.shp]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.shx]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.dbf]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.prj]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [cb_2018_us_nation_20m.cpg]
[2026-04-02 17:28:00] INFO       [MainThread][geospatial_tools.utils] Extracted: [S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml]

[['/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.shp.ea.iso.xml',
  '/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.shp.iso.xml',
  '/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.shp',
  '/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.shx',
  '/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.dbf',
  '/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.prj',
  '/home/dev/projects/geospatial-tools/data/cb_2018_us_nation_20m.cpg'],
 ['/home/dev/projects/geospatial-tools/data/S2A_OPER_GIP_TILPAR_MPC__20151209T095117_V20150622T000000_21000101T000000_B00.kml']]

### Initial pre-processing

The above layers were processed using QGIS.

For the purpose of this analysis, only the contiguous lower 48 states have been conserved; smaller islands/land masses 
have also been striped.

The S2 tiling grid has been trimmed to keep only the grid cells that overlap with the 
contiguous states.

Since our area of study is quite large, the `EPSG:5070` projection was chosen, as it
covers the whole area, introduces minimal distortion while preserving area.

The files below have also been saved in this repository.

In [4]:
USA_POLYGON_FILE = DATA_DIR / "usa_polygon_5070.gpkg"
S2_USA_GRID_FILE = DATA_DIR / "s2_grid_usa_polygon_5070.gpkg"
usa_polygon = gpd.read_file(USA_POLYGON_FILE)
s2_grid = gpd.read_file(S2_USA_GRID_FILE)

In [5]:
usa_polygon

,AFFGEOID,GEOID,NAME,geometry
0,0100000US,US,United States,"MULTIPOLYGON (((-2116048.733 3142966.552, -211..."

In [6]:
s2_grid

,name,folders,description,geometry
0,12TUP,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1386334.944 2487548.77 0, -..."
1,12TYQ,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-976300.478 2523767.452 0, -..."
2,12TYR,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-960099.705 2622374.255 0, -..."
3,12TYN,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1008622.024 2325748.358 0, ..."
4,12TYP,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-992478.385 2424861.34 0, -8..."
...,...,...,...,...
977,12TTM,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1515431.586 2304192.826 0, ..."
978,12TUK,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1448525.813 2089886.667 0, ..."
979,12TUQ,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1371006.917 2586590.133 0, ..."
980,12TUR,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1355793.563 2685354.08 0, -..."
981,12TUN,Features,TILE PROPERTIES<br><table border=0 cellpadding...,"MULTIPOLYGON Z (((-1401759.785 2388321.4 0, -1..."

In [7]:
m = leafmap.Map(center=[40, -98], zoom=4)

# In blue, the USA polygon
m.add_gdf(usa_polygon, layer_name='usa')
# In red, the Sentinel 2 grid
m.add_gdf(s2_grid, layer_name='s2_grid', style={"color": "red"})

m

Map(center=[40, -98], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_te…

## Creating our grid

From this, we want to create a grid of square polygons with which we will later on
query the [Planetary Computer](https://planetarycomputer.microsoft.com/dataset/sentinel-2-l2a)
Sentinel 2 dataset and clip the selected Sentinel 2 images.

For the purpose of this notebook, the grid that will be created will use 10km by 10km squares to speed up 
processing.

In [8]:
grid_size = 5000
bbox = usa_polygon.total_bounds
grid_5km_filename = DATA_DIR / "polygon_grid_5km.gpkg"

In [9]:
print("Starting processing for [create_vector_grid_parallel]")
grid_5km = create_vector_grid_parallel(bounding_box=bbox, grid_size=grid_size, crs="EPSG:5070")
print(f"Printing len(grid_parallel) to check if grid contains same amount of polygons : {len(grid_5km)}")
to_geopackage(gdf=grid_5km, filename=grid_5km_filename)

Starting processing for [create_vector_grid_parallel]
[2026-04-02 17:28:01] INFO       [MainThread][geospatial_tools.vector] Creating grid coordinates for bounding box [[-2356113.74289801   301469.31619713  2258154.44089948  3165721.6501298 ]]
[2026-04-02 17:28:01] INFO       [MainThread][geospatial_tools.vector] Creating flattened grid coordinates
[2026-04-02 17:28:01] INFO       [MainThread][geospatial_tools.vector] Number of workers used: 16
[2026-04-02 17:28:01] INFO       [MainThread][geospatial_tools.vector] Allocating polygon array for [528879] polygons
[2026-04-02 17:28:01] INFO       [MainThread][geospatial_tools.vector] Creating polygons from chunks
[2026-04-02 17:28:05] INFO       [MainThread][geospatial_tools.vector] Managing properties
[2026-04-02 17:28:05] INFO       [MainThread][geospatial_tools.utils] Creating EPSG code from following input : [EPSG:5070]
[2026-04-02 17:28:05] INFO       [MainThread][geospatial_tools.vector] Creating spatial index
[2026-04-02 17:28:05] INFO       [MainThread][geospatial_tools.vector] Generating polygon UUIDs
Printing len(grid_parallel) to check if grid contains same amount of polygons : 528879
[2026-04-02 17:28:07] INFO       [MainThread][geospatial_tools.vector] Starting writing process
[2026-04-02 17:28:10] INFO       [MainThread][geospatial_tools.vector] File [/home/dev/projects/geospatial-tools/data/polygon_grid_5km.gpkg] took 3.3827707767486572 seconds to write.

PosixPath('/home/dev/projects/geospatial-tools/data/polygon_grid_5km.gpkg')

In [10]:
grid_5km

,geometry,feature_id
0,"POLYGON ((-2356113.743 301469.316, -2351113.74...",ec75a129-ddf6-44cf-95e1-b51e70228399
1,"POLYGON ((-2351113.743 301469.316, -2346113.74...",c970f076-7059-4a86-9f35-ed702f017423
2,"POLYGON ((-2346113.743 301469.316, -2341113.74...",7c62f9f8-934d-45e3-a439-3a2389de4012
3,"POLYGON ((-2341113.743 301469.316, -2336113.74...",656dbf77-6940-4d52-a292-fa3472cb2481
4,"POLYGON ((-2336113.743 301469.316, -2331113.74...",4c9d715b-71ee-4aec-8345-81bf87fc7951
...,...,...
528874,"POLYGON ((2233886.257 3161469.316, 2238886.257...",7a60b2db-a198-4972-a034-08840d11095f
528875,"POLYGON ((2238886.257 3161469.316, 2243886.257...",128ae73b-e96e-49f2-84c9-1f15352b1f11
528876,"POLYGON ((2243886.257 3161469.316, 2248886.257...",2e1d6d10-d55a-4ccd-8137-6e9670c1a90c
528877,"POLYGON ((2248886.257 3161469.316, 2253886.257...",b4859991-92ec-4c9c-8fd0-5c3b0c422494
528878,"POLYGON ((2253886.257 3161469.316, 2258886.257...",1949821d-cc04-4143-ac08-e91eedccd968

### Selecting the useful polygons

Now, since our grid was created using the extent of our input polygon (continental USA), we need to filter out the polygons that do not intersect with it.

Doing this in Python is not the most efficient way to do things, but since it's a step that shouldn't be done over and over, it's not that critical.

If ever you need to do this step in an efficient way because the data is just too big or too complex, it would be better off going through QGIS, PyGQIS, GDAL or 
some other more efficient way to do this operation.

In [11]:
intersecting_polygons_filename = DATA_DIR / "intersecting_polygon_grid_5km.gpkg"
print("Starting intersect selection")
intersecting_polygons = select_polygons_by_location(grid_5km, usa_polygon, num_of_workers=4)

# Optionally save to a new file
to_geopackage(intersecting_polygons, intersecting_polygons_filename)

Starting intersect selection
[2026-04-02 17:28:10] INFO       [MainThread][geospatial_tools.vector] Number of workers used: 4
[2026-04-02 17:28:10] INFO       [MainThread][geospatial_tools.vector] Concatenating results
[2026-04-02 17:28:17] INFO       [MainThread][geospatial_tools.vector] Creating spatial index
[2026-04-02 17:28:17] INFO       [MainThread][geospatial_tools.vector] Filtering columns of the results
[2026-04-02 17:28:17] INFO       [MainThread][geospatial_tools.vector] Starting writing process
[2026-04-02 17:28:19] INFO       [MainThread][geospatial_tools.vector] File [/home/dev/projects/geospatial-tools/data/intersecting_polygon_grid_5km.gpkg] took 2.063347101211548 seconds to write.

PosixPath('/home/dev/projects/geospatial-tools/data/intersecting_polygon_grid_5km.gpkg')

In [12]:
intersecting_polygons

,geometry,feature_id
774,"POLYGON ((1513886.257 301469.316, 1518886.257 ...",5d284fce-67b3-441c-81fd-afee3e79f35b
775,"POLYGON ((1518886.257 301469.316, 1523886.257 ...",c56cb374-93eb-48c9-adf2-23ba6b84dee0
776,"POLYGON ((1523886.257 301469.316, 1528886.257 ...",96c8e283-4de7-468b-a9e5-aa1a89f623f4
777,"POLYGON ((1528886.257 301469.316, 1533886.257 ...",877d7635-f38f-47f7-904d-c722f534edf1
1365,"POLYGON ((-146113.743 306469.316, -141113.743 ...",84290da6-a04d-4df3-b468-9b66d1b2ade4
...,...,...
528034,"POLYGON ((-1966113.743 3161469.316, -1961113.7...",dc8056c4-fa45-42d7-95da-f8b81b3833a1
528035,"POLYGON ((-1961113.743 3161469.316, -1956113.7...",86871398-6656-4dca-b90c-ebe4c4cebbec
528036,"POLYGON ((-1956113.743 3161469.316, -1951113.7...",27417181-cde2-407b-abba-b9722afbc1c1
528037,"POLYGON ((-1951113.743 3161469.316, -1946113.7...",f1fa73a6-c3de-4c0f-b162-17b62d8d226f
528038,"POLYGON ((-1946113.743 3161469.316, -1941113.7...",faafcff6-99c4-4933-85a2-b3b1fea1919e

### Visualizing the selected polygons

This will take more or less time, depending on the number on polygons.

(Do not try this with a grid size smaller than 10000m)

In [ ]:
### This takes a few minutes and navigation will be slow.
# Map is zoomed in to help with processing

m_intersecting_polygons = leafmap.Map(center=[39.7, -123], zoom=10)
m_intersecting_polygons.add_gdf(intersecting_polygons, layer_name='intersecting_polygons', style={"color": "blue"})
m_intersecting_polygons

## Data processing pipeline prototype

### Finding the best image for each S2 tiling grid

In [ ]:
# This is the full list of S2 grids
s2_tile_grid_list = s2_grid["name"].to_list()
s2_tile_grid_list

In [ ]:
# The list is a bit long, so we'll be continuing this notebook with the following subset
s2_tile_grid_subset_list = ["10TDK", "10TEK", "10SEJ", "10SDJ"]

### Building our processing list

First, let's make create a subselection of our dataset

In [ ]:
S2_USA_GRID_FILE = DATA_DIR / "s2_grid_usa_polygon_5070.gpkg"
s2_grid = gpd.read_file(S2_USA_GRID_FILE)
s2_grid

In [ ]:
# Creating our S2 grid tile subset

S2_USA_GRID_SUBSET_FILE = DATA_DIR / "s2_grid_usa_polygon_5070_subset.gpkg"
s2_grid_subset = s2_grid[s2_grid["name"].isin(s2_tile_grid_subset_list)]

# Optionally save to geopackage
to_geopackage(gdf=s2_grid_subset, filename=S2_USA_GRID_SUBSET_FILE)

In [ ]:
s2_grid_subset

In [ ]:
# Creating our polygon grid subset

intersect_polygons_subset_filename = DATA_DIR / "intersecting_polygon_grid_5km_subset.gpkg"
print("Starting intersect selection")
intersect_polygons_subset = select_polygons_by_location(intersecting_polygons, s2_grid_subset, predicate="within", num_of_workers=4)
# intersect_polygons_subset = gpd.read_file(intersect_polygons_subset_filename)

# Optionally save to a new file
to_geopackage(intersect_polygons_subset, intersect_polygons_subset_filename)

In [ ]:
intersect_polygons_subset

### Finding the best products for our subset use case

In [ ]:
# `s2_feature_name_columns` is the name of the column in `s2_grid_subset` where the id of
# the different tiles is found.
#
# `vector_column_name` is the name of the column in which the best results will be stored

s2_feature_name_columns = "name"
vector_column_name = "s2_tiles"

# Initiating our client
best_products_client = BestProductsForFeatures(sentinel2_tiling_grid=s2_grid_subset,
                                               sentinel2_tiling_grid_column=s2_feature_name_columns,
                                               vector_features=intersect_polygons_subset,
                                               vector_features_column=vector_column_name,
                                               max_cloud_cover=15)

In [ ]:
# Executing the search
#
# This search look only for complete products, meaning products with less than
# 5 percent of nodata.

start_year = 2023
end_year = 2024
start_month = 6
end_month = 7

best_products_client.create_date_ranges(start_year, end_year, start_month, end_month)
products = best_products_client.find_best_complete_products()
products

In [ ]:
# Selecting the best products for each vector tile
# This step is necessary as some of our vector polygons can be withing multiple S2 tiles.
# The best available S2 tile is therefore selected for each vector polygon.

best_results_path = DATA_DIR / "vector_tiles_with_s2tiles_subset.gpkg"
best_results = best_products_client.select_best_products_per_feature()
to_geopackage(best_results, best_results_path)

In [ ]:
best_results

### Visualizing the results

In [ ]:
best_products_client.successful_results

In [ ]:
# We do, however, have one S2 grid missing
# No complete products where found for that tile.
# Therefore, it will have to be processed separately later, 
# by mosaicing different products together
#
# The consequence of this is that all vector polygons that are
# within this tile will not be processed at this time.

best_products_client.incomplete_results

In [ ]:
m_best_results = leafmap.Map(center=[39.7, -123], zoom=8)
m_best_results.add_gdf(s2_grid_subset, layer_name='s2_tiles', style={"color": "red"})
m_best_results.add_gdf(best_results, layer_name='vector_tiles_s2_grid', style={"color": "green"})
m_best_results

In [ ]:
group_by_product = best_results.groupby("best_s2_product_id")["feature_id"].agg(list).reset_index()
group_by_product

In [ ]:
product_list = group_by_product["best_s2_product_id"].tolist()
product_list

In [ ]:
product_example_id = product_list[0]
product_example_id

### Downloading and processing Sentinel 2 products

#### Downloading and preparing Sentinel 2 products

In [ ]:
product_asset_list = []
bands = ["B02", "B03", "B04", "B08", "visual"]
download_directory = DATA_DIR / "example_s2_download_and_processing"

for p in product_list:
    processed_product = download_and_process_sentinel2_asset(product_id=p, 
                                                             product_bands=bands,
                                                             base_directory=download_directory,
                                                             target_projection=5070)
                                                    
    product_asset_list.append(processed_product)

In [ ]:
for p in product_asset_list:
    print(f"Asset ID : [{p.asset_id}]")
    print(f"Reprojected ID path : \n[{p.reprojected_asset_path}]\n")

In [ ]:
# Here, we are creating a new Asset object simply for convenience, from the printed outputs above

product = Asset(asset_id=product_example_id,
                reprojected_asset=download_directory / f"{product_example_id}_reprojected.tif", )

#### Creating a new geodataframe of all the vector polygons that are within our selected product

In [ ]:
s2_product_id = product.asset_id
product_path = product.reprojected_asset_path
product_id_series = group_by_product[group_by_product["best_s2_product_id"] == s2_product_id]
# Since it's grouped by product id, there should always be only one row in the series
feature_ids = product_id_series["feature_id"].iloc[0]
vector_features = best_results[best_results["feature_id"].isin(feature_ids)]
vector_features_path = DATA_DIR / "vector_features.gpkg"
to_geopackage(vector_features, DATA_DIR / "vector_features.gpkg")

print(vector_features)

#### Creating our Sentinel 2 "chips" by clipping main products with our vector polygon grid

In [ ]:
clip_raster_with_polygon(raster_image=product_path,
                         polygon_layer=vector_features_path,
                         base_output_filename=s2_product_id,
                         output_dir=download_directory / "test_sentinel2_clip")